t = (1:ii)/(3600/dt);
figure(1),subplot(2,1,1),plot(t(1:ii),Pd(1:ii,:),(1:jj)/60,Ph(1:jj,:));
xlim([0 24]);
set(gca,'xTick',0:4:24);
legend('Sensor','SC','Bat','Solar','Vibra');
xlabel('Time(h)'),ylabel('Power(W)');
subplot(2,1,2),plot(t(1:ii),V(1:ii,:));
xlim([0 24]);
set(gca,'xTick',0:4:24);
legend('Battery','SC');
xlabel('Time(h)'),ylabel('Voltage(V)');

% figure(2);
% [AX,H1,H2] = plotyy((1:jj)/60,Ph(1:jj,1),(1:jj)/60,En(1:jj,1),'plot');
% set(gca,'xTick',0:4:24);
% set(AX,'xlim',[0 24]);
% set(AX(1),'XColor','k','YColor','b');
% set(AX(2),'XColor','k','YColor','r');
% HH1=get(AX(1),'Ylabel');
% set(HH1,'String','Power(W)');
% set(HH1,'color','b');
% HH2=get(AX(2),'Ylabel');
% set(HH2,'String','Irradiance(W/m^2)');
% set(HH2,'color','r');
% set(H1,'LineStyle','-');
% set(H1,'color','b');
% set(H2,'LineStyle',':');
% set(H2,'color','r');
% legend([H1,H2],{'Solar Energy Harvested';'Irradiance'});
% xlabel('Time(h)');
% title('Solar Energy Harvested');
% 
% figure(3);
% [AX,H1,H2] = plotyy((1:jj)/60,Ph(1:jj,2),(1:jj)/60,En(1:jj,2),'plot');
% set(gca,'xTick',0:4:24);
% set(AX,'xlim',[0 24]);
% set(AX(1),'XColor','k','YColor','b');
% set(AX(2),'XColor','k','YColor','r');
% HH1=get(AX(1),'Ylabel');
% set(HH1,'String','Power(W)');
% set(HH1,'color','b');
% HH2=get(AX(2),'Ylabel');
% set(HH2,'String','Wind Speed(m/s)');
% set(HH2,'color','r');
% set(H1,'LineStyle','-');
% set(H1,'color','b');
% set(H2,'LineStyle',':');
% set(H2,'color','r');
% legend([H1,H2],{'Vibration Energy Harvested';'Wind Speed'});
% xlabel('Time(h)');
% title('Vibration Energy Harvested');